version: "3"
services:
  database:
    build: ./database
    ports: 
      - "4321:5432"
    # environment:
    #   - proxy=http://proxy/
  
  spider:
    build: ./spider
    # ports: 
    #   - "9003:80"
    depends_on:
      - database

  searcher:
    build: ./searcher
    ports: 
      - "8080:8080"
    depends_on:
      - database
